version: '3.7' # specify docker-compose version
 
# Define the services/containers to be run
services:
 frontend:
   build: ./frontend
   ports:
     - "80:4200"
     - "4005:4005"
   container_name: frontend
   command: 
    - sh
    - -c
    - |
      npm install
      envsubst < ./src/environments/environment.template.ts > ./src/environments/environment.ts
      npm run start
   environment:
    - API_URL=http://localhost:8080/
    - CHOKIDAR_USEPOLLING=true
    - NODE_ENV=dev
    - TZ=Europe/Lisbon
   volumes:
    - "./frontend:/app"
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
 backend:
   build: ./backend
   ports:
     - "8080:8080"
   environment:
     - MONGO_URL=mongodb://database/rede_emprega_db
     - TZ=Europe/Lisbon
   links:
     - database
   container_name: backend
   depends_on:
     - database
   volumes:
      - "./backend:/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
   links:
      - redis:redis
 database: # name of the third service
   container_name: database
   image: mongo:4.4 # specify image to build container from
   environment:
    MONGO_INITDB_ROOT_USERNAME: redemprega
    MONGO_INITDB_ROOT_PASSWORD: w32*113kf'ad_234sknb
    MONGO_INITDB_DATABASE: rede_emprega_db
    TZ: Europe/Lisbon
   restart: always
   ports:
     - "27017:27017" # specify port forewarding
   volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
 redis:
   container_name: redis
   image: "redis:alpine"

 backup:
   container_name: backup
   build: ./backup
   depends_on:
      - database
   environment:
      - AWS_ACCESS_KEY_ID=AKIAUM26AIJWAMMLTUGJ
      - AWS_SECRET_ACCESS_KEY=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
      - BUCKET=sf4f2a3523a5sj3fdm358xmrjs9r
      - BACKUP_FOLDER=dev/db/
      - INIT_BACKUP=true
      - TZ=Europe/Lisbon
      - CRON_TZ=Europe/Lisbon
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_USER=redEmprega
      - MONGODB_PASS=g9rFv+fm3i56<RszP
      - MONGODB_DB=rede_emprega_db